description: >
  Build the artifact of a FastAPI application

docker:
  - image: cimg/python:3.10.2

resource_class: small

parameters:
  project_name:
    description: The name of the project being deployed
    type: string

steps:
  - checkout

  - attach_workspace:
      at: .

  - run:
      name: Run "make build"
      command: |
        # We'll just do an echo here for now since this job
        # is just part of an example.
        echo "Building <<parameters.project_name>>"
